const perk = (details, condition = '', availability = 'Available') => ({status: 'Provided', details, condition, availability, verified: true, type: 'Included benefit'});
const unknown = {status: 'Not announced', details: 'Not announced', verified: false, availability: 'Unknown'};
export function seedState() {
  return {
    version: 1,
    profile: {name: 'Aarav', fullName: 'Aarav Sharma', course: 'Computer Science · 3rd year', interests: ['Technology', 'Design'], skills: 'React, UI design', availability: '6 hours / week', discoverable: false, shareStreak: false, reminders: true},
    events: [
      {id: 'hack', title: 'Build something that matters.', shortTitle: 'Hack the Campus 2026', category: 'Hackathon', club: 'Google Developer Group', date: '2026-10-10', deadline: '2026-10-05', venue: 'Innovation Hub · Block A', published: true, cover: 'hack', tagline: 'HACK THE CAMPUS', description: 'One campus. A hundred possibilities. Team up to build a practical solution to a real campus problem in this 24-hour hackathon.', eligibility: 'Open to all undergraduate students. Teams of 2–4.', requirements: ['A team of 2–4 students', 'A 300-word idea abstract', 'A working prototype at the final showcase'], food: perk('Lunch included', 'For registered participants'), goodies: perk('Welcome kit', 'First 100 registrants · Stock not confirmed', 'Unknown'), reason: 'Matches your interest in technology and design', teamNeed: 'Frontend developer + designer', updated: '2 Oct, 9:15 AM', source: 'GDG campus announcement · Revision 2'},
      {id: 'design', title: 'Make your first impression count.', shortTitle: 'Design beyond the pixels', category: 'Workshop', club: 'The Design Collective', date: '2026-10-07', deadline: '2026-10-06', venue: 'Design Studio · Library Annex', published: true, cover: 'design', tagline: 'BEYOND THE PIXELS', description: 'A hands-on workshop on making digital experiences more thoughtful. Bring your curiosity and leave with a portfolio-ready case study.', eligibility: 'All students welcome. No design experience needed.', requirements: ['Bring a laptop', 'Install a design tool of your choice'], food: perk('Coffee & snacks', 'Included with attendance'), goodies: unknown, reason: 'A little inspiration for your next design project', teamNeed: 'Individual participation', updated: '1 Oct, 4:30 PM', source: 'Design Collective notice · Revision 1'},
      {id: 'pitch', title: 'Big ideas start with a small pitch.', shortTitle: 'The Startup Launchpad', category: 'Competition', club: 'Entrepreneurship Cell', date: '2026-10-14', deadline: '2026-10-09', venue: 'Main Auditorium', published: true, cover: 'pitch', tagline: 'IDEA TO IMPACT', description: 'Turn a promising idea into a compelling pitch. Get feedback from founders and meet students who want to build what comes next.', eligibility: 'Student teams of 1–3. Early-stage ideas welcome.', requirements: ['A five-slide pitch deck', 'A three-minute presentation'], food: unknown, goodies: perk('Founder notebook', 'Included for presenting teams'), reason: 'An opportunity to put your building skills to work', teamNeed: 'Product & business', updated: '1 Oct, 11:00 AM', source: 'E-Cell event notice · Revision 1'},
      {id: 'open', title: 'Find your people. Find your project.', shortTitle: 'Open Source Saturday', category: 'Community', club: 'Open Source Club', date: '2026-10-17', deadline: '2026-10-15', venue: 'Computer Lab 3', published: true, cover: 'open', tagline: 'COMMIT TOGETHER', description: 'Your first pull request starts here. Pair with other students, explore welcoming projects, and contribute something useful.', eligibility: 'All years and branches. Basic Git knowledge helps.', requirements: ['A GitHub account', 'A laptop with Git installed'], food: perk('Pizza after the sprint', 'Included for attendees'), goodies: perk('Contributor stickers', 'For completed contributions'), reason: 'Matches your declared React skills', teamNeed: 'Developers of every level', updated: '2 Oct, 10:00 AM', source: 'Open Source Club announcement · Revision 1'}
    ],
    saved: ['hack'],
    tasks: [
      {id: 'abstract', eventId: 'hack', title: 'Draft your hackathon idea abstract', due: '2026-10-03', status: 'upcoming', qualifying: true, owner: 'You', dependency: null, evidence: false},
      {id: 'roles', eventId: 'hack', title: 'Confirm your team’s roles', due: '2026-10-04', status: 'upcoming', qualifying: true, owner: 'You', dependency: null, evidence: false},
      {id: 'submit', eventId: 'hack', title: 'Review and submit your final abstract', due: '2026-10-05', status: 'upcoming', qualifying: true, owner: 'You', dependency: 'abstract', evidence: true}
    ],
    credits: ['2026-09-28','2026-09-29','2026-09-30','2026-10-01'].map((day, i) => ({taskId: 'historical-' + i, day})),
    invitations: [{id: 'in-1', name: 'Ishita Rao', initials: 'IR', role: 'UI / UX designer', direction: 'incoming', status: 'pending', eventId: 'hack'}],
    people: [{id: 'maya', name: 'Maya Patel', initials: 'MP', role: 'Frontend developer', skills: 'React · TypeScript · CSS', availability: '6 hours / week', color: 'lavender'}, {id: 'rohan', name: 'Rohan Mehta', initials: 'RM', role: 'Backend developer', skills: 'Python · APIs · PostgreSQL', availability: '8 hours / week', color: 'peach'}, {id: 'zoya', name: 'Zoya Khan', initials: 'ZK', role: 'Product designer', skills: 'Figma · Research · Prototyping', availability: '4 hours / week', color: 'mint'}],
    changes: [{id: 'change-1', eventId: 'hack', previous: '2026-10-07', updated: '2026-10-05', status: 'pending'}],
    buddy: {name: 'Dev Mehta', initials: 'DM', count: 3, creditedToday: false, accepted: true},
    outcomes: [], drafts: [], activity: [],
    role: 'student'
  };
}
